config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
      resources :users
      resources :posts
      resources :admin_users

      root to: "users#index"
    end
  resources :posts do
    member do
      get :approve
    end
  end
  
  devise_for :users, skip:[:registrations]
  root to: 'static#homepage'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Overtime App Alert", sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Overtime App Error", sticky: false) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Overtime App Notification", sticky: false) %>
<% end %>

app/views/shared/_audit_log_tab.html.erb
<li class="<%= active?(audit_logs_path) %>">
  <%= link_to "Audit Log", audit_logs_path, class: 'nav-link nav-item' %>
</li>

app/views/shared/_nav.html.erb
<div class="logo">
    <h1>Time Tracker</h1>
</div>

<% if current_user %>
    <ul class="nav nav-tabs custom-nav">
        <%= nav_helper 'li','nav-item nav-link' %>
        <%= render 'shared/audit_log_tab'if policy(AuditLog).index? %>

        <li class="nav-item dropdown ml-md-auto">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Account</a>
            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <% if current_user.try(:type) == 'AdminUser'  %>    
                    <li>
                        <%= link_to "Admin Dashboard", admin_root_path, class:'dropdown-item'%>
                    <li class="dropdown-divider"> </li> 
                <% end %>
                    <li>    
                        <%= link_to "Logout", destroy_user_session_path, method: :delete ,class:'dropdown-item'%>
                    </li>
            </ul>
        </li>
    </ul>
<% end %>